# Generated by Django 4.2.1 on 2023-05-31 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
