# Generated by Django 4.2.1 on 2023-05-31 22:25

import adminpage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_usersmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='tell',
            field=models.CharField(blank=True, default='+998', max_length=13, null=True, validators=[adminpage.models.validate_tell_num]),
        ),
    ]
