# Generated by Django 4.2.1 on 2023-06-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_usersmodel_is_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersmodel',
            old_name='is_block',
            new_name='is_blocked',
        ),
    ]
