# Generated by Django 4.2.1 on 2023-06-01 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0007_alter_usersmodel_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersmodel',
            name='is_blocked',
        ),
    ]
