# Generated by Django 4.2.1 on 2023-06-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0008_remove_usersmodel_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
