# Generated by Django 4.2.1 on 2023-06-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0009_usersmodel_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_title', models.CharField(max_length=25)),
                ('message_description', models.TextField()),
                ('message_date', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'AdminMessageModel',
            },
        ),
    ]
