# Generated by Django 4.2.1 on 2023-05-23 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import userpage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surename', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=255)),
                ('tell', models.CharField(blank=True, default='+998', max_length=13, null=True, validators=[userpage.models.validate_tell_num])),
                ('market_name', models.CharField(blank=True, default='market', max_length=25, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ClientModel',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'Units',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=25)),
                ('price', models.FloatField(default=0)),
                ('date', models.DateField(null=True)),
                ('sum_price', models.FloatField(blank=True, default=0, null=True)),
                ('quantity_product', models.FloatField()),
                ('to_pay', models.FloatField(blank=True, default=0, null=True)),
                ('debt', models.FloatField(blank=True, default=0, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userpage.clientmodel')),
                ('unit', models.ForeignKey(blank=True, default='birliklar', null=True, on_delete=django.db.models.deletion.CASCADE, to='userpage.unit')),
            ],
            options={
                'db_table': 'ProductModel',
            },
        ),
    ]
