# Generated by Django 4.2.1 on 2023-06-02 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0002_productmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='product_name',
            field=models.ForeignKey(max_length=25, on_delete=django.db.models.deletion.CASCADE, to='userpage.product'),
        ),
    ]
