# Generated by Django 4.2.2 on 2023-06-07 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0010_alter_productmodel_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_name',
            field=models.ForeignKey(max_length=25, null=True, on_delete=django.db.models.deletion.CASCADE, to='userpage.product'),
        ),
    ]
